const wrapper = document.querySelector(".wrapper"),
selectBtn = wrapper.querySelector(".select-btn"),
searchInp = wrapper.querySelector("input"),
options = wrapper.querySelector(".options");

let countries = ["Aberdeen City",
                "Aberdeenshire",
                "Adur",
                "Allerdale",
                "Alnwick",
                "Amber Valley",
                "Angus",
                "Argyll and Bute",
                "Arun",
                "Ashfield",
                "Ashford",
                "Aylesbury Vale",
                "Babergh",
                "Barking and Dagenham",
                "Barnet",
                "Barnsley",
                "Barrow-in-Furness",
                "Basildon",
                "Basingstoke and Deane",
                "Bassetlaw",
                "Bath and North East Somerset",
                "Bedford",
                "Berwick-upon-Tweed",
                "Bexley",
                "Birmingham",
                "Blaby",
                "Blackburn with Darwen",
                "Blackpool",
                "Blaenau Gwent",
                "Blyth Valley",
                "Bolsover",
                "Bolton",
                "Boston",
                "Bournemouth",
                "Bracknell Forest",
                "Bradford",
                "Braintree",
                "Breckland",
                "Brent",
                "Brentwood",
                "Bridgend",
                "Bridgnorth",
                "Brighton and Hove",
                "Bristol",
                "Broadland",
                "Bromley",
                "Bromsgrove",
                "Broxbourne",
                "Broxtowe",
                "Burnley",
                "Bury",
                "Caerphilly",
                "Calderdale",
                "Cambridge",
                "Camden",
                "Cannock Chase",
                "Canterbury",
                "Caradon",
                "Cardiff",
                "Carlisle",
                "Carmarthenshire",
                "Carrick",
                "Castle Morpeth",
                "Castle Point",
                "Central Bedfordshire",
                "Ceredigion",
                "Charnwood",
                "Chelmsford",
                "Cheltenham",
                "Cherwell",
                "Cheshire East",
                "Cheshire West and Chester",
                "Chester",
                "Chesterfield",
                "Chester-le-Street",
                "Chichester",
                "Chiltern",
                "Chorley",
                "Christchurch",
                "City of London",
                "Clackmannanshire",
                "Colchester",
                "Congleton",
                "Conwy",
                "Copeland",
                "Corby",
                "Cornwall",
                "Cotswold",
                "County Durham",
                "Coventry",
                "Craven",
                "Crawley",
                "Crewe and Nantwich",
                "Croydon",
                "Dacorum",
                "Darlington",
                "Dartford",
                "Daventry",
                "Denbighshire",
                "Derby",
                "Derbyshire Dales",
                "Derwentside",
                "Doncaster",
                "Dover",
                "Dudley",
                "Dumfries and Galloway",
                "Dundee City",
                "Durham",
                "Ealing",
                "Easington",
                "East Ayrshire",
                "East Cambridgeshire",
                "East Devon",
                "East Dorset",
                "East Dunbartonshire",
                "East Hampshire",
                "East Hertfordshire",
                "East Lindsey",
                "East Lothian",
                "East Northamptonshire",
                "East Renfrewshire",
                "East Riding of Yorkshire",
                "East Staffordshire",
                "Eastbourne",
                "Eastleigh",
                "Eden",
                "Edinburgh",
                "Ellesmere Port and Neston",
                "Elmbridge",
                "Enfield",
                "Epping Forest",
                "Epsom and Ewell",
                "Erewash",
                "Exeter",
                "Falkirk",
                "Fareham",
                "Fenland",
                "Fife",
                "Flintshire",
                "Forest Heath",
                "Forest of Dean",
                "Fylde",
                "Gateshead",
                "Gedling",
                "Glasgow City",
                "Gloucester",
                "Gosport",
                "Gravesham",
                "Great Yarmouth",
                "Greenwich",
                "Guildford",
                "Gwynedd",
                "Hackney",
                "Halton",
                "Hambleton",
                "Hammersmith and Fulham",
                "Harborough",
                "Haringey",
                "Harlow",
                "Harrogate",
                "Harrow",
                "Hart",
                "Hartlepool",
                "Hastings",
                "Havant",
                "Havering",
                "Herefordshire",
                "Hertsmere",
                "High Peak",
                "Highland",
                "Hillingdon",
                "Hinckley and Bosworth",
                "Horsham",
                "Hounslow",
                "Huntingdonshire",
                "Hyndburn",
                "Inverclyde",
                "Ipswich",
                "Isle of Anglesey",
                "Isle of Wight",
                "Islington",
                "Kennet",
                "Kensington and Chelsea",
                "Kerrier",
                "Kettering",
                "King's Lynn and West Norfolk",
                "Kingston upon Hull",
                "Kingston upon Thames",
                "Kirklees",
                "Knowsley",
                "Lambeth",
                "Lancaster",
                "Leeds",
                "Leicester",
                "Lewes",
                "Lewisham",
                "Lichfield",
                "Lincoln",
                "Liverpool",
                "London Airport (Heathrow)",
                "Luton",
                "Macclesfield",
                "Maidstone",
                "Maldon",
                "Malvern Hills",
                "Manchester",
                "Mansfield",
                "Medway",
                "Melton",
                "Mendip",
                "Merthyr Tydfil",
                "Merton",
                "Mid Bedfordshire",
                "Mid Devon",
                "Mid Suffolk",
                "Mid Sussex",
                "Middlesbrough",
                "Midlothian",
                "Milton Keynes",
                "Mole Valley",
                "Monmouthshire",
                "Moray",
                "Neath Port Talbot",
                "New Forest",
                "Newark and Sherwood",
                "Newcastle upon Tyne",
                "Newcastle-under-Lyme",
                "Newham",
                "Newport",
                "North Ayrshire",
                "North Cornwall",
                "North Devon",
                "North Dorset",
                "North East Derbyshire",
                "North East Lincolnshire",
                "North Hertfordshire",
                "North Kesteven",
                "North Lanarkshire",
                "North Lincolnshire",
                "North Norfolk",
                "North Shropshire",
                "North Somerset",
                "North Tyneside",
                "North Warwickshire",
                "North West Leicestershire",
                "North Wiltshire",
                "Northampton",
                "Northumberland",
                "Norwich",
                "Nottingham",
                "Nuneaton and Bedworth",
                "Oadby and Wigston",
                "Oldham",
                "Orkney Islands",
                "Oswestry",
                "Oxford",
                "Pembrokeshire",
                "Pendle",
                "Penwith",
                "Perth and Kinross",
                "Peterborough",
                "Plymouth",
                "Poole",
                "Portsmouth",
                "Powys",
                "Preston",
                "Purbeck",
                "Reading",
                "Redbridge",
                "Redcar and Cleveland",
                "Redditch",
                "Reigate and Banstead",
                "Renfrewshire",
                "Restormel",
                "Rhondda, Cynon, Taff",
                "Ribble Valley",
                "Richmond upon Thames",
                "Richmondshire",
                "Rochdale",
                "Rochford",
                "Rossendale",
                "Rother",
                "Rotherham",
                "Rugby",
                "Runnymede",
                "Rushcliffe",
                "Rushmoor",
                "Rutland",
                "Ryedale",
                "Salford",
                "Salisbury",
                "Sandwell",
                "Scarborough",
                "Scottish Borders",
                "Sedgefield",
                "Sedgemoor",
                "Sefton",
                "Selby",
                "Sevenoaks",
                "Sheffield",
                "Shepway",
                "Shetland Islands",
                "Shrewsbury and Atcham",
                "Shropshire",
                "Slough",
                "Solihull",
                "South Ayrshire",
                "South Bedfordshire",
                "South Bucks",
                "South Cambridgeshire",
                "South Derbyshire",
                "South Gloucestershire",
                "South Hams",
                "South Holland",
                "South Kesteven",
                "South Lakeland",
                "South Lanarkshire",
                "South Norfolk",
                "South Northamptonshire",
                "South Oxfordshire",
                "South Ribble",
                "South Shropshire",
                "South Somerset",
                "South Staffordshire",
                "South Tyneside",
                "Southampton",
                "Southend-on-Sea",
                "Southwark",
                "Spelthorne",
                "St. Albans",
                "St. Edmundsbury",
                "St. Helens",
                "Stafford",
                "Staffordshire Moorlands",
                "Stevenage",
                "Stirling",
                "Stockport",
                "Stockton-on-Tees",
                "Stoke-on-Trent",
                "Stratford-upon-Avon",
                "Stroud",
                "Suffolk Coastal",
                "Sunderland",
                "Surrey Heath",
                "Sutton",
                "Swale",
                "Swansea",
                "Swindon",
                "Tameside",
                "Tamworth",
                "Tandridge",
                "Taunton Deane",
                "Teesdale",
                "Teignbridge",
                "Telford and Wrekin",
                "Tendring",
                "Test Valley",
                "Tewkesbury",
                "Thanet",
                "The Vale of Glamorgan",
                "Three Rivers",
                "Thurrock",
                "Tonbridge and Malling",
                "Torbay",
                "Torfaen",
                "Torridge",
                "Tower Hamlets",
                "Trafford",
                "Tunbridge Wells",
                "Tynedale",
                "Uttlesford",
                "Vale of White Horse",
                "Vale Royal",
                "Wakefield",
                "Walsall",
                "Waltham Forest",
                "Wandsworth",
                "Wansbeck",
                "Warrington",
                "Warwick",
                "Watford",
                "Waveney",
                "Waverley",
                "Wealden",
                "Wear Valley",
                "Wellingborough",
                "Welwyn Hatfield",
                "West Berkshire",
                "West Devon",
                "West Dorset",
                "West Dunbartonshire",
                "West Lancashire",
                "West Lindsey",
                "West Lothian",
                "West Oxfordshire",
                "West Somerset",
                "West Wiltshire",
                "Western Isles",
                "Westminster",
                "Weymouth and Portland",
                "Wigan",
                "Wiltshire",
                "Winchester",
                "Windsor and Maidenhead",
                "Wirral",
                "Woking",
                "Wokingham",
                "Wolverhampton",
                "Worcester",
                "Worthing",
                "Wrexham",
                "Wychavon",
                "Wycombe",
                "Wyre",
                "Wyre Forest",
                "York"];

function addCountry(selectedCountry) {
    options.innerHTML = "";
    countries.forEach(country => {
        let isSelected = country == selectedCountry ? "selected" : "";
        let li = `<li onclick="updateName(this)" class="${isSelected}">${country}</li>`;
        options.insertAdjacentHTML("beforeend", li);
    });
}
addCountry();

function updateName(selectedLi) {
    searchInp.value = "";
    addCountry(selectedLi.innerText);
    wrapper.classList.remove("active");
    selectBtn.firstElementChild.innerText = selectedLi.innerText;
}

searchInp.addEventListener("keyup", () => {
    let arr = [];
    let searchWord = searchInp.value.toLowerCase();
    arr = countries.filter(data => {
        return data.toLowerCase().startsWith(searchWord);
    }).map(data => {
        let isSelected = data == selectBtn.firstElementChild.innerText ? "selected" : "";
        return `<li onclick="updateName(this)" class="${isSelected}">${data}</li>`;
    }).join("");
    options.innerHTML = arr ? arr : `<p style="margin-top: 10px;">Oops! Country not found</p>`;
});

selectBtn.addEventListener("click", () => wrapper.classList.toggle("active"));